name: Build

on:
  push:
    branches:
        - main
        - feat/*
  pull_request:


jobs:
  format:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo pip install virtualenv
          virtualenv env --python=python3
          cd env
          source bin/activate
          pip install -r .\requirements.txt
